# Generated by Django 4.2 on 2023-04-29 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LittleLemonAPI", "0002_order_orderitem_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="menu_item",
            new_name="menuitem",
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "menuitem")},
        ),
    ]
